### ISSUE TITLE
EPIC | Web app desktop version

### ISSUE THREAD

**Issue by thesocialdev** [AletheiaFact/aletheia#378]
### Background Information
The AletheiaFact web app is a mobile-first design MVP. In order to improve UI/UX for users in the desktop version, we should start designing the desktop interfaces for the existing pages

### Acceptance Criteria
- [ ] Design | Elaborate general structure for the desktop version 
- [ ] Design | Home page desktop version
- [ ] Design | Personality page desktop version
- [ ] Design | Claim page desktop version
- [ ] Design | Claim Review page desktop version
